[PE-37] Feature/37-create-contract
mchekini-check-consulting/pro-epargne-api pull request #2
Opened 2024-01-31 20:38 UTC by yacinebenkaidali

## Description

- [ ] Create entities `in` DTOs
- [ ] Created Contract
- [ ] Created Company
- [ ] Created CompanySignatory
- [ ] Created PeeContribution
- [ ] Created PerecoContribution
- [ ] Create Contract `out` DTO

2024-02-02 13:39 UTC, mchekini-check-consulting requested changes

2024-02-02 13:39 UTC, mchekini-check-consulting commented on src/main/java/com/checkconsulting/proepargne/dto/collaborator/CollaboratorInDto.java
> +// @AllArgsConstructor
A quoi sert cette classe ?

2024-02-02 13:39 UTC, mchekini-check-consulting commented on src/main/java/com/checkconsulting/proepargne/dto/contract/ContractInDTO.java
> +public record ContractInDTO(
Y'a t'il un avantage d'utiliser un record ?

2024-02-02 13:39 UTC, mchekini-check-consulting commented on src/main/java/com/checkconsulting/proepargne/dto/contract/PeeContributionDTO.java
> +        private boolean peeProfitSharingAccepte;
il manquerait pas un d pour accepted ?

2024-02-02 13:39 UTC, mchekini-check-consulting commented on src/main/java/com/checkconsulting/proepargne/dto/contract/PercoContributionDTO.java
> +        private boolean percoTimeSavingAccountAccepte;
idem

2024-02-02 13:39 UTC, mchekini-check-consulting commented on src/main/java/com/checkconsulting/proepargne/model/Company.java
> +    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
le siren d'une entreprise ne doit pas être auto généré

2024-02-02 13:39 UTC, mchekini-check-consulting commented on src/main/java/com/checkconsulting/proepargne/model/PeeContribution.java
> +    @MapsId
A quoi sert le MapsId ?

2024-02-02 13:39 UTC, mchekini-check-consulting commented on src/main/java/com/checkconsulting/proepargne/model/PercoContribution.java
> +    private Long contractId;
y'a t'il pas une duplication sur le contract Id qui est aussi présent dans le contrat ?

2024-02-02 13:39 UTC, mchekini-check-consulting commented on src/main/java/com/checkconsulting/proepargne/resources/ApplicationInformationResource.java
> +        log.info("un appel a ete effectue");
on peut profiter pour le supprimer, c'était juste un exemple de démo

2024-02-02 13:39 UTC, mchekini-check-consulting commented on src/main/java/com/checkconsulting/proepargne/resources/ContractResource.java
> +    public ResponseEntity<?> getAllContacts() {
a t'on besoin de récupérer tous les contrats ? Est ce que ça rentre dans le cadre de cette US ?

2024-02-02 13:39 UTC, mchekini-check-consulting commented on src/main/java/com/checkconsulting/proepargne/services/ContractService.java
> +                Company company = new Company();
Je pense qu'on peut garder un mapping manuel pour cette fois ci.

On pourra faire un refacto par la suite pour utiliser une bibliothèque de mapping

2024-02-02 14:04 UTC, mchekini-check-consulting requested changes

2024-02-02 14:04 UTC, mchekini-check-consulting commented on src/main/resources/db/migration/V0.0.5__rename-pereco-to-perco.sql
> +ALTER TABLE IF EXISTS pereco_contribution RENAME TO perco_contribution;
Pourquoi changer le nom de la table ? ça va surement provoquer des problèmes aux autres devs

Ce genre de modifications doit être prise en équipe idéalement

2024-02-03 09:12 UTC, yacinebenkaidali commented on src/main/java/com/checkconsulting/proepargne/dto/collaborator/CollaboratorInDto.java
> +// @AllArgsConstructor
on n'est plus besoin de cette class

2024-02-03 09:14 UTC, yacinebenkaidali commented on src/main/java/com/checkconsulting/proepargne/dto/contract/ContractInDTO.java
> +public record ContractInDTO(
J'aimerai utiliser un record quand on est besoin que des getters et parce qu’il sont une fonctionnalité natif du java (pas besoin d’une librairie)

2024-02-03 11:32 UTC, yacinebenkaidali commented on src/main/java/com/checkconsulting/proepargne/model/PeeContribution.java
> +    @MapsId
c'est pour qu'on puisse utiliser le meme id pour les deux entites

2024-02-03 11:33 UTC, yacinebenkaidali commented on src/main/java/com/checkconsulting/proepargne/model/PercoContribution.java
> +    private Long contractId;
Ca ne sera pas un champ suppliementaire au nivuea de la base de donnees, mais spring est besoin de ce champ pour pouvoir re-utiliser le id du contract

2024-02-03 11:33 UTC, yacinebenkaidali commented on src/main/java/com/checkconsulting/proepargne/resources/ContractResource.java
> +    public ResponseEntity<?> getAllContacts() {
Oui vous avez reaison, c'est juste pour tester

2024-02-03 13:13 UTC, yacinebenkaidali commented on src/main/resources/db/migration/V0.0.5__rename-pereco-to-perco.sql
> +ALTER TABLE IF EXISTS pereco_contribution RENAME TO perco_contribution;
C'est note, pour des futures version, je vais notifie l'equipe en premier

2024-02-06 09:57 UTC, yacinebenkaidali commented
No longer needed

2024-02-06 09:57 UTC, closed without merging